image : microsoft/aspnetcore-build:latest
stages:
 - compile
 - test
 - build
compile:
 stage: compile
 script:
  - 'dotnet restore'
  - 'dotnet build'
test:
 stage: test
 script: 
  - 'dotnet test MovieCruiser.Test/MovieCruiser.Test.csproj'
build:
 stage: build
 script:
   - 'dotnet publish MovieCruiser.Service -c Release'
 artifacts:
  expire_in: 1 month
  paths:
   - MovieCruiser.Service/bin/Release/netcoreapp2.0/publish/