image: microsoft/aspnetcore-build:latest
stages:
  - compile
  - test
  - publish
  compile:
    stage: compile
    script:
      - 'dotnet restore'
      - 'dotnet build'
  test:
    stage: test
    script: 
      - 'dotnet test MovieCruiser.Test/MovieCruiser.Test.csproj'
  publish:
    stage: publish
    script:
      - 'dotnet publish MovieCruiser.Service -c Release'
    artifacts:
      expire_in: 1 month
      paths:
        - MovieCruiser.Service/bin/Release/netcoreapp2.0/publish/
        


